channels:
- defaults
- conda-forge

dependencies:
- astropy
- astropy-healpix
- astroquery
- jupyter
- matplotlib=2.2.2
- nbconvert
- nbformat
- numpy
- pytest
- pytest-cov
- requests
- six
- sphinx
- pip:
  - numpydoc
  - pytest-profiling
  - networkx
  - spherical_geometry
