channels:
- defaults
- conda-forge

dependencies:
- astropy
- astropy-healpix
- matplotlib
- pytest
- pytest-cov
- sphinx
- pip:
  - numpydoc
  - astropy-sphinx-theme
  - networkx
  - spherical_geometry
  - lark-parser
  - cdshealpix
