name: mocpy-dev

channels:
- defaults
- conda-forge

dependencies:
- astropy
- astroquery
- astropy_healpix
- requests
- matplotlib # Used in fill and border
- networkx # Used in get_boundaries
- spherical-geometry